require "cancan"
require "cancan_edit/edit_ability"
require "cancan_edit/edit_additions"
require "cancan_edit/edit_rule"
require "cancan_edit/controller_additions"
require "cancan_edit/formtastic_inputs_boolean_input.rb"
require "cancan_edit/formtastic_inputs_check_boxes_input.rb"
